### ISSUE TITLE
Create new protobuf API

### ISSUE THREAD

**Issue by oubiwann** [clojusc/protobuf#27]
Following on from the exploration done in #18, we're going to create a new API for end users of this library.

Tasks:

* [x] Move current code from `protobuf.core` to `protobuf.impl.flatland.*`
* [x] Improve the organization of the code that's moved to `protobuf.impl.flatland.*`
* [x] Create a protocol in `protobuf.core` and pull in behaviours and records for `extend` from `impl.*`
* [x] In `protobuf.impl.flatland.core` just have a `FlatlandProtoBuf` record and its corresponding behaviour `def`
* [x] Have `ProtoBuf` implementation records take a compiled Java protobuf class (inner) as a field, e.g.,:
```clj
    (->MyProtoBuf :protobuf-class Example$Person)
```
* [x] Figure out a static method approach for schema rendering
* [x] Display instance data when printing protobuf impl in the REPL
* [x] Improve usability of protobuf impl with core seq and map functions
* [x] Update the docs to reflect all these changes

**Comment by oubiwann** [comment]
Done.
