### ISSUE TITLE
Provide full support for proto3

### ISSUE THREAD

**Issue by oubiwann** [clojusc/protobuf#32]
Tasks:
* [ ] Add proto3 examples
* [ ] Add proto3 tests
* [ ] Add proto3 support for default value in enums - #30

**Comment by oubiwann** [comment]
There's a `proto3` example here:
 * https://github.com/google/protobuf/blob/master/examples/addressbook.proto

**Update:** Added.

**Comment by oubiwann** [comment]
The more I read about proto3, the less I like it :-( The changes were pretty drastic, from the perspective of schema-based data applications (or RPC services). I may end up back-burnering this task. I'd accept a PR for a good solution that didn't effect the usability of proto2 ...

**Comment by oubiwann** [comment]
I guess I should claify that last comment:

1. I'm still working on supporting `proto3` ;-)
1. The comment was made after exploring the possibility of converting everything to `proto3`, since it and `proto2` are wire-compatible ...
1. The explorations were a dismal failure, and I did a lot of reading to learn more about all the changes between versions and their implications, in an effort to determine a level of effort in moving everything in this project to `proto3` ... 

On a side note, I did come across [Cap'n Protocol](https://capnproto.org/) (by the author of Protocol Buffers v2), and that looks _really_ nice; too bad Google won't adopt it :-(

**Comment by mattyulrich** [comment]
This is a great expansion of the flatland impl.  The interface is simple as expected.  Thanks for the work on this!

I'm experiencing something that may be attributable to this issue/epic - when I deserialize proto3 schemas that have enums with 0 vals, the enum seems to just drop out of the message.  Is this expected until proto3 is fully supported?

Thanks again for the library!

**Comment by smessems** [comment]
Hi, is there any update?

**Comment by oubiwann** [comment]
Sadly, no :-( 

I don't suspect I'll have the time to work on `proto3` any time in the near future, so this will likely need to be a community contribution/PR.

It's an interesting problem to tackle; wish I had more availability for it.

**Comment by smessems** [comment]
Thanks. Would it be possible to maybe lay out some info you gained while investigating this?
